ALTER TABLE "ResumeBuilderProfile"
ADD COLUMN "photoPositionX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "photoPositionY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN "photoScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
